// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pandami.Data;

namespace Pandami.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210119150259_v1.1")]
    partial class v11
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Pandami.Models.CategorieAide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Categorie")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategorieAide");
                });

            modelBuilder.Entity("Pandami.Models.Disponibilite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DebutHeure")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FinHeure")
                        .HasColumnType("datetime2");

                    b.Property<short?>("JourId")
                        .HasColumnType("smallint");

                    b.Property<int?>("MembreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValiditeDebutDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValiditeFinDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JourId");

                    b.HasIndex("MembreId");

                    b.ToTable("Disponibilites");
                });

            modelBuilder.Entity("Pandami.Models.Feat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("AcceptationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AnnulationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ClotureDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EnCoursRealisation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FinFeatHelper")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HeureDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HeureFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RealisationDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("SommeAvancee")
                        .HasColumnType("real");

                    b.Property<DateTime>("SommePrevoir")
                        .HasColumnType("datetime2");

                    b.Property<float>("SommeRembourseeDate")
                        .HasColumnType("real");

                    b.Property<DateTime>("SurPlace")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Feats");
                });

            modelBuilder.Entity("Pandami.Models.JourDeLaSemaine", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .UseIdentityColumn();

                    b.Property<string>("NomDuJour")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JourDeLaSemaines");
                });

            modelBuilder.Entity("Pandami.Models.Materiel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("NomMateriel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Materiel");
                });

            modelBuilder.Entity("Pandami.Models.Membre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Inscription")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date");

                    b.Property<string>("Mdp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Naissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prenom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SexeId")
                        .HasColumnType("int");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SexeId");

                    b.ToTable("Membres");
                });

            modelBuilder.Entity("Pandami.Models.Repondre", b =>
                {
                    b.Property<int>("IdMembre")
                        .HasColumnType("int");

                    b.Property<int>("IdFeat")
                        .HasColumnType("int");

                    b.Property<DateTime>("AcceptationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DesistementDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdMembre", "IdFeat");

                    b.HasIndex("IdFeat");

                    b.ToTable("Repondres");
                });

            modelBuilder.Entity("Pandami.Models.Sexe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("NomSexe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Sexes");
                });

            modelBuilder.Entity("Pandami.Models.Suspension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DebutDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FinDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MembreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MembreId");

                    b.ToTable("Suspensions");
                });

            modelBuilder.Entity("Pandami.Models.TypeAide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CategorieAideId")
                        .HasColumnType("int");

                    b.Property<int?>("MaterielId")
                        .HasColumnType("int");

                    b.Property<string>("NomAide")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategorieAideId");

                    b.HasIndex("MaterielId");

                    b.ToTable("TypeAides");
                });

            modelBuilder.Entity("Pandami.Models.Disponibilite", b =>
                {
                    b.HasOne("Pandami.Models.JourDeLaSemaine", "Jour")
                        .WithMany()
                        .HasForeignKey("JourId");

                    b.HasOne("Pandami.Models.Membre", null)
                        .WithMany("Disponibilites")
                        .HasForeignKey("MembreId");

                    b.Navigation("Jour");
                });

            modelBuilder.Entity("Pandami.Models.Feat", b =>
                {
                    b.HasOne("Pandami.Models.TypeAide", "Type")
                        .WithMany("Feats")
                        .HasForeignKey("TypeId");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Pandami.Models.Membre", b =>
                {
                    b.HasOne("Pandami.Models.Sexe", "Sexe")
                        .WithMany()
                        .HasForeignKey("SexeId");

                    b.Navigation("Sexe");
                });

            modelBuilder.Entity("Pandami.Models.Repondre", b =>
                {
                    b.HasOne("Pandami.Models.Feat", "Feat")
                        .WithMany("Reponses")
                        .HasForeignKey("IdFeat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pandami.Models.Membre", "Membre")
                        .WithMany("Inscriptions")
                        .HasForeignKey("IdMembre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feat");

                    b.Navigation("Membre");
                });

            modelBuilder.Entity("Pandami.Models.Suspension", b =>
                {
                    b.HasOne("Pandami.Models.Membre", null)
                        .WithMany("Suspensions")
                        .HasForeignKey("MembreId");
                });

            modelBuilder.Entity("Pandami.Models.TypeAide", b =>
                {
                    b.HasOne("Pandami.Models.CategorieAide", "CategorieAide")
                        .WithMany()
                        .HasForeignKey("CategorieAideId");

                    b.HasOne("Pandami.Models.Materiel", "Materiel")
                        .WithMany()
                        .HasForeignKey("MaterielId");

                    b.Navigation("CategorieAide");

                    b.Navigation("Materiel");
                });

            modelBuilder.Entity("Pandami.Models.Feat", b =>
                {
                    b.Navigation("Reponses");
                });

            modelBuilder.Entity("Pandami.Models.Membre", b =>
                {
                    b.Navigation("Disponibilites");

                    b.Navigation("Inscriptions");

                    b.Navigation("Suspensions");
                });

            modelBuilder.Entity("Pandami.Models.TypeAide", b =>
                {
                    b.Navigation("Feats");
                });
#pragma warning restore 612, 618
        }
    }
}
