// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pandami.Data;

namespace Pandami.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Pandami.Models.Feat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("AcceptationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AnnulationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ClotureDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EnCoursRealisation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FinFeatHelper")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HeureDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HeureFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RealisationDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("SommeAvancee")
                        .HasColumnType("real");

                    b.Property<DateTime>("SommePrevoir")
                        .HasColumnType("datetime2");

                    b.Property<float>("SommeRembourseeDate")
                        .HasColumnType("real");

                    b.Property<DateTime>("SurPlace")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Feats");
                });

            modelBuilder.Entity("Pandami.Models.Membre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Inscription")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Mdp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Naissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Membres");
                });

            modelBuilder.Entity("Pandami.Models.Repondre", b =>
                {
                    b.Property<int>("IdMembre")
                        .HasColumnType("int");

                    b.Property<int>("IdFeat")
                        .HasColumnType("int");

                    b.Property<DateTime>("AcceptationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DesistementDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdMembre", "IdFeat");

                    b.HasIndex("IdFeat");

                    b.ToTable("Repondre");
                });

            modelBuilder.Entity("Pandami.Models.Repondre", b =>
                {
                    b.HasOne("Pandami.Models.Feat", "Feat")
                        .WithMany("Reponses")
                        .HasForeignKey("IdFeat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pandami.Models.Membre", "Membre")
                        .WithMany("Inscriptions")
                        .HasForeignKey("IdMembre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feat");

                    b.Navigation("Membre");
                });

            modelBuilder.Entity("Pandami.Models.Feat", b =>
                {
                    b.Navigation("Reponses");
                });

            modelBuilder.Entity("Pandami.Models.Membre", b =>
                {
                    b.Navigation("Inscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
